apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replica: 2
  selector:
    matchLabels:
      app: myapp-fastapi
  template:
    metadata:
      labels:
        app: myapp-fastapi
    spec:
      containers:
      - name: fastapi-app
        image: thullyodev/myapp-fastapi:v4
        ports:
        - containerport: 5000

